import type { NextPage } from 'next';
import { Box, Header, ImageWrapped, TitleDescImg, ItemBox } from 'Components';
import Layer1 from 'Components/Page/Layer1';
import Layer2 from 'Components/Page/Layer2';
import Layer3 from 'Components/Page/Layer3';
import img1 from 'public/img1.jpeg';
import img2 from 'public/img2.jpeg';
import img3 from 'public/img3.jpeg';
import Frida from 'public/Frida.webp';
import womanLookDown from 'public/womanLookDown.webp';
import { createRef, useRef } from 'react';
import Head from 'next/head';
import { Parallax, ParallaxLayer } from '@react-spring/parallax';

// import { createClient } from 'next-sanity';

// const client = createClient({
//     projectId: '3zonnd0w',
//     dataset: 'production',
//     apiVersion: '2022-08-28',
//     useCdn: false,
// });

const imgPropsObj = {
    layout: 'responsive',
    objectFit: 'cover',
    objectPosition: 'top',
};

const Home: NextPage = () => {
    return (
        <Box className="">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layer1 />
            <Layer2 />
            <Layer3 />
        </Box>
    );
};

export default Home;

// export async function getStaticProps() {
//     const article = await client.fetch(`*[_type == "article"]`);
//     console.log(article, 'data');
//     return {
//         props: { article },
//     };
// }
